// <auto-generated />
using Gym.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gym.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20191102071614_SmallChange")]
    partial class SmallChange
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gym.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Exercise_Description")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Exercise_Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Gym.Models.GymMember", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Membership_End_Date")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Planned_exercise_id")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("PersonID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Gym.Models.PlannedWorkout", b =>
                {
                    b.Property<int>("ExerciseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Exercise_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Planned_Reps")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Planned_Set_Number")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Planned_Weight")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("ExerciseID");

                    b.ToTable("PlannedWorkouts");
                });

            modelBuilder.Entity("Gym.Models.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Occupation")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("StaffID");

                    b.ToTable("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
